on: push

name: CI

env:
  TZ: Asia/Tokyo

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - run: make node_modules
      - run: make lint
      - run: make typecheck
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HEADLESS: true
      FORCE_FULL_FETCH: true
      FEED_ITEMS_NUMBER: 2
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: make node_modules
      - run: make run
