on: push

name: CI

env:
  TZ: Asia/Tokyo
  MAKE_YARN_FROZEN_LOCKFILE: 1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"
      - name: ESLint
        run: make lint
      - name: Prettier
        run: make format.check
      - name: Typecheck
        run: make typecheck
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HEADLESS: true
      FORCE_FULL_FETCH: true
      FEED_ITEMS_NUMBER: 2
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Run
        run: make run
