on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"

name: Deploy

env:
  TZ: Asia/Tokyo

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HEADLESS: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: dist
          path: dist
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make node_modules
      - name: Run
        run: make run
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: dist
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: run
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
