on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */1 * * *"

name: Deploy

env:
  TZ: Asia/Tokyo

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HEADLESS: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          ref: dist
          path: dist
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - run: make node_modules
      - name: Run
        run: make run
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: dist
          publish_dir: ./dist
